name: Tests
on:
  pull_request:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  test:
    runs-on: ubuntu-latest

    name: Tests
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      # - uses: denoland/setup-deno@v1
      #   with:
      #     deno-version: v1.x
      - run: curl -fsSL https://deno.land/x/install/install.sh | sh
      - run: echo "$HOME/.deno/bin" > $GITHUB_PATH

      - name: Verify formatting
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Start redis server
        uses: ./.github/actions/redis
        with:
          UPSTASH_REDIS_REST_URL: http://127.0.0.1:6379
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_AUTH_TOKEN }}
          UPSTASH_REPO_ACCESS_TOKEN: ${{ secrets.UPSTASH_REPO_ACCESS_TOKEN }}
          REDIS_SERVER_CONFIG: ${{ secrets.REDIS_SERVER_CONFIG }}

      - name: Run tests
        run: deno test -A --fail-fast --shuffle
        env:
          UPSTASH_REDIS_REST_URL: http://127.0.0.1:6379
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_AUTH_TOKEN }}

      - name: Build
        run: deno run -A ./cmd/build.ts

      - name: Size limit
        run: node_modules/.bin/size-limit
        working-directory: dist
