name: Tests
on:
  pull_request:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install bun
        run: npm install -g bun

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun run test
